groupweb/urls.py
from django.urls import path

from . import views

app_name = 'groupweb'
urlpatterns = [
    path('', views.index_view, name='index'),
    path('research', views.research_view, name='research'),
    # path('research', views.ResearchView.as_view(), name='research'),
    path('members', views.member_view, name='members'),
    path('publications', views.publication_view, name='publications'),
    path('opportunities', views.opportunities_view, name='opportunities'),
]

webproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from groupweb.feeds import AllPostsRssFeed

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('groupweb.urls')),

    # 记得在顶部引入 AllPostsRssFeed
    path('all/rss/', AllPostsRssFeed(), name='rss'),
]

urlpatterns += staticfiles_urlpatterns()

groupweb/models.py
import re

import markdown
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.html import strip_tags
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension


def generate_rich_content(value):
    md = markdown.Markdown(
        extensions=[
            "markdown.extensions.extra",
            "markdown.extensions.codehilite",
            # 记得在顶部引入 TocExtension 和 slugify
            TocExtension(slugify=slugify),
        ]
    )
    content = md.convert(value)
    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    toc = m.group(1) if m is not None else ""
    return {"content": content, "toc": toc}


class PlainPage(models.Model):

    name = models.CharField("PageName", max_length=100)
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = "PlainPage"
        verbose_name_plural = verbose_name

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse("groupweb:detail", kwargs={"pk": self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=["views"])

    def rich_content(self):
        return generate_rich_content(self.body)

    def __str__(self):
        return self.name


class Category(models.Model):
    """
    Django 要求模型必须继承 models.Model 类。
    Category 只需要一个简单的分类名 name 就可以了。
    CharField 指定了分类名 name 的数据类型，CharField 是字符型，
    CharField 的 max_length 参数指定其最大长度，超过这个长度的分类名就不能被存入数据库。
    当然 Django 还为我们提供了多种其它的数据类型，如日期时间类型 DateTimeField、整数类型 IntegerField 等等。
    Django 内置的全部类型可查看文档：
    https://docs.djangoproject.com/en/2.2/ref/models/fields/#field-types
    """

    name = models.CharField("分类名", max_length=100)

    class Meta:
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """

    name = models.CharField("标签名", max_length=100)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField("标题", max_length=70)

    # 文章正文，我们使用了 TextField。
    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用 TextField 来存储大段文本。
    body = models.TextField("正文")

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用 DateTimeField 类型。
    created_time = models.DateTimeField("创建时间", default=timezone.now)
    modified_time = models.DateTimeField("修改时间")

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField("摘要", max_length=200, blank=True)

    # 这是分类与标签，分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类、标签对应的数据库表关联了起来，但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    # 且自 django 2.0 以后，ForeignKey 必须传入一个 on_delete 参数用来指定当关联的数据被删除时，被关联的数据的行为，
    # 我们这里假定当某个分类被删除时，该分类下全部文章也同时被删除，因此使用 models.CASCADE 参数，意为级联删除。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/2.2/topics/db/models/#relationships
    category = models.ForeignKey(Category, verbose_name="分类", on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name="标签", blank=True)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User, verbose_name="作者", on_delete=models.CASCADE)

    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0, editable=False)

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        ordering = ["-created_time"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.modified_time = timezone.now()

        # 首先实例化一个 Markdown 类，用于渲染 body 的文本。
        # 由于摘要并不需要生成文章目录，所以去掉了目录拓展。
        md = markdown.Markdown(
            extensions=["markdown.extensions.extra", "markdown.extensions.codehilite",]
        )

        # 先将 Markdown 文本渲染成 HTML 文本
        # strip_tags 去掉 HTML 文本的全部 HTML 标签
        # 从文本摘取前 54 个字符赋给 excerpt
        self.excerpt = strip_tags(md.convert(self.body))[:54]

        super().save(*args, **kwargs)

    # 自定义 get_absolute_url 方法
    # 记得从 django.urls 中导入 reverse 函数
    def get_absolute_url(self):
        return reverse("groupweb:detail", kwargs={"pk": self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=["views"])

    @property
    def toc(self):
        return self.rich_content.get("toc", "")

    @property
    def body_html(self):
        return self.rich_content.get("content", "")

    @cached_property
    def rich_content(self):
        return generate_rich_content(self.body)

groupweb/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView

# from pure_pagination.mixins import PaginationMixin
from .instance_models import GroupMember, Publication

from .models import Category, Post, Tag


def index_view(request):
    context = {}
    return render(request, 'index.html', context)


def research_view(request):
    context = {}
    return render(request, 'Research.html', context)


def member_view(request):
    context = {}
    member_list = []
    lingzhi = GroupMember(name='lingzhi', position='student', bio='Hi, I am lingzhi')
    member_list.append(lingzhi)
    context = {'member_list': member_list}
    return render(request, 'Group_members.html', context)


def publication_view(request):
    context = {}
    publication_list = []
    with open('groupweb/static/txt_info/Publications/Soft_mat') as f:
        soft_mat_publication_list = f.readlines()
    # pub1 = Publication(title='test title', journal='test journal', doi='test doi')
    # publication_list.append(pub1)
    context = {'soft_mat_publication_list':soft_mat_publication_list, 'publication_list': publication_list}
    return render(request, 'Publications.html', context)


def opportunities_view(request):
    context = {}
    return render(request, 'Opportunities.html', context)

# class IndexView(ListView):
#     model = Post
#     template_name = "index.html"

#
# # 记得在顶部导入 DetailView
# class PostDetailView(DetailView):
#     # 这些属性的含义和 ListView 是一样的
#     model = Post
#     template_name = "groupweb/detail.html"
#     context_object_name = "post"
#
#     def get(self, request, *args, **kwargs):
#         # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
#         # get 方法返回的是一个 HttpResponse 实例
#         # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
#         # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
#         response = super().get(request, *args, **kwargs)
#
#         # 将文章阅读量 +1
#         # 注意 self.object 的值就是被访问的文章 post
#         self.object.increase_views()
#
#         # 视图必须返回一个 HttpResponse 对象
#         return response

templates/Group_members.html
{% extends 'bases/base.html' %}
{% load static %}

{% block main %}
    <div class=text-center>
      <h1>
          <b>Our group members</b>
      </h1>
        <br>
        <br>
    </div>

    <div class=text-left>
      <p style="font-size: x-large">
          <br>Professor Dan Li
          <br>Dr Wenjie Jiang
          <br>Dr Lianhai Zu
          <br>Dr Peiyao Wang
          <br>Dr Yang Cao
      </p>
    </div>
    <br>
    <br>

    <h1>Bio list</h1>
    <div>
    {% block group_member_info %}
        {% if member_list %}
            {% for member in member_list %}
                <p style="font-size: x-large">
                Name: {{ member.name }}<br>
                Position: {{ member.position }}<br>
                Bio: {{ member.bio }}<br>
                </p>
            {% endfor %}
        {% endif %}
    {% endblock group_member_info %}
    </div>
{% endblock main %}

templates/Opportunities.html
{% extends 'bases/base.html' %}
{% load static %}

{% block main %}
    <div class=text-center>
      <h1>
          <b>Opportunities in systems ionic lab</b>
      </h1>
        <br>
        <br>
    </div>
    <div class=text-left>
      <p style="font-size: x-large">
          We are hiring!
      </p>
    </div>
{% endblock main %}

templates/Publications.html
{% extends 'bases/base.html' %}
{% load static %}

{% block main %}
    <h1 class=text-center>
      <b>Selected publications in systems ionic lab</b>
    </h1>
    <br>
    <br>


    <h1 class="text-center">Soft materials</h1>
    {% block publication_info %}
        {% if soft_mat_publication_list %}
            {% for pub in soft_mat_publication_list %}
                <p style="font-size: x-large">
                {{ pub }}
                </p>
            {% endfor %}
        {% endif %}
    {% endblock publication_info %}

{% endblock main %}

templates/Research.html
{% extends 'bases/base.html' %}
{% load static %}

{% block main %}
    <div class=text-center>
      <h1>
          <b>Our research interests</b>
      </h1>
        <br>
        <br>
    </div>

    <div class=text-left>
      <p style="font-size: x-large">
          Graphene-based 2D materials
      </p>
      <p style="font-size: x-large">
          Ionotronics
      </p>
      <p style="font-size: x-large">
          Energy storage and conversion devices
      </p>
      <p style="font-size: x-large">
          To be finalised...
      </p>
    </div>
{% endblock main %}

templates/bases/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    {#brower tab name#}
    <title>Systems Ionics Lab</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'groupweb/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'groupweb/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'groupweb/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'groupweb/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'groupweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'groupweb/js/pace.min.js' %}"></script>
    <script src="{% static 'groupweb/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            {# Web logo and title #}
            <div class="col-md-4 col-sm-8 col-xs-9">
                <div class="logo">
                    <h1>
                        <a href="{% url 'groupweb:index' %}"><img src="{% static 'groupweb/img/test3.png' %}" alt=""
                                                                  width="35px"></a>
                        <a href="{% url 'groupweb:index' %}">Systems Ionics Lab</a>
                    </h1>
                </div>
            </div>

            {# navbar #}
            <div class="col-md-8 col-sm-4 col-xs-3">
                <nav class="main-nav" role="navigation">
                    {# navigation bar overlay button (for mobile) #}
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    {# navigation bar content #}
                    <div class="collapse navbar-collapse" id="pc end navbar">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'groupweb:index' %}"
                                                        data-hover="About us">About us</a></li>
                            <li class="cl-effect-11"><a href="{% url 'groupweb:research' %}"
                                                        data-hover="Research">Research</a></li>
                            <li class="cl-effect-11"><a href="{% url 'groupweb:members' %}"
                                                        data-hover="Group members">Group members</a></li>
                            <li class="cl-effect-11"><a href="{% url 'groupweb:publications' %}"
                                                        data-hover="Publications">Publications</a></li>
                            <li class="cl-effect-11"><a href="{% url 'groupweb:opportunities' %}"
                                                        data-hover="Opportunities">Opportunities</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% block main %}
                    {# inbetween this block is expected to show other contents depends on the child page #}
                {% endblock main %}
            </main>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2023 Systems Ionics Lab, The Department of Chemical Engineering, The
                    University of Melbourne</p>
            </div>
        </div>
    </div>
</footer>


<!-- Mobile Menu -->
<div class="overlay nav overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'groupweb:index' %}">About us</a></li>
            <li><a href="{% url 'groupweb:research' %}">Research</a></li>
            <li><a href="{% url 'groupweb:members' %}">Group members</a></li>
            <li><a href="{% url 'groupweb:publications' %}">Publications</a></li>
            <li><a href="{% url 'groupweb:opportunities' %}">Opportunities</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'groupweb/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
</body>
</html>

templates/bases/base_bkp.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html>
<head>
    {#brower tab name#}
    <title>Systems Ionics Lab</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'groupweb/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'groupweb/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'groupweb/css/custom.css' %}">

    <!-- js -->
    <script src="{% static 'groupweb/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'groupweb/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'groupweb/js/pace.min.js' %}"></script>
    <script src="{% static 'groupweb/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
{#        <div class="row">#}
            {# Web logo and title #}
{#            <div class="col-md-4 col-sm-5 col-xs-8">#}
{#                <div class="logo">#}
{#                    <h1>#}
{#                        <a href="{% url 'groupweb:index' %}"><img src="{% static 'groupweb/img/test.jpeg' %}" alt=""#}
{#                                                                  width="40px"></a>#}
{#                        <a href="{% url 'groupweb:index' %}">Systems Ionics Lab</a>#}
{#                    </h1>#}
{#                </div>#}
{#            </div>#}
{##}
            {# navbar #}
{#            <div class="col-md-8 col-sm-7 col-xs-5">#}
{#                <nav class="main-nav" role="navigation">#}
                    {# navigation bar overlay button (for mobile) #}
{#                    <div class="navbar-header">#}
{#                        <button type="button" id="trigger-overlay" class="navbar-toggle">#}
{#                            <span class="ion-navicon"></span>#}
{#                        </button>#}
{#                    </div>#}
{##}
                    {# navigation bar content #}
{#                    <div class="collapse navbar-collapse" id="pc end navbar">#}
{#                        <ul class="nav navbar-nav navbar-right">#}
{#                            <li class="cl-effect-11"><a href="{% url 'groupweb:index' %}"#}
{#                                                        data-hover="About us">About us</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'groupweb:research' %}"#}
{#                                                        data-hover="Research">Research</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'groupweb:members' %}"#}
{#                                                        data-hover="Group members">Group members</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'groupweb:publications' %}"#}
{#                                                        data-hover="Publications">Publications</a></li>#}
{#                            <li class="cl-effect-11"><a href="{% url 'groupweb:opportunities' %}"#}
{#                                                        data-hover="Opportunities">Opportunities</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </nav>#}
{#            </div>#}
{#        </div>#}
    </header>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
</div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-12">
                {% block main %}
                    {#            inbetween this block is expected to show other contents depends on the child page#}
                {% endblock main %}
            </main>
        </div>
    </div>
</div>

<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">2023 Systems Ionics Lab, The Department of Chemical Engineering, The University
                    of Melbourne</p>
            </div>
        </div>
    </div>
</footer>


<!-- Mobile Menu -->
<div class="overlay nav overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li class="cl-effect-14"><a href="{% url 'groupweb:index' %}">About us</a></li>
            <li class="cl-effect-14"><a href="{% url 'groupweb:research' %}">Research</a></li>
            <li class="cl-effect-14"><a href="{% url 'groupweb:members' %}">Group members</a></li>
            <li class="cl-effect-14"><a href="{% url 'groupweb:publications' %}">Publications</a></li>
            <li class="cl-effect-14"><a href="{% url 'groupweb:opportunities' %}">Opportunities</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'groupweb/js/script.js' %}"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'bases/base.html' %}
{% load static %}

{% block main %}
    <div class=text-center>
      <h1>
          <b>Systems Ionic Lab</b>
      </h1>
        <br>
        <br>
    </div>
    <figure class="img-responsive-center" title="Group photo">
      <img class="img-responsive" src="{% static 'groupweb/img/test2.jpeg' %}" alt="Test Image" width="800px">
    </figure>
    <div class=text-left>
      <p style="font-size: x-large">
          We are a research group in the department of Chemical Engineering, The University of Melbourne.
          Our research is focusing on the ion transport in nanoporous materials and future ionotronics.
          Currently, we have many posdocs and many PhD students.
          We are a big warm family.
      </p>
    </div>
{% endblock main %}